name: Deploy static site

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Inject the secret into a tiny JS file
      - name: Create config
        env:
          HOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          echo "export const webhook = '$HOOK';" > config.secret.js

      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
